### ISSUE TITLE
Path resolution bug in klocalizer can lead to AssertionError

### ISSUE THREAD

**Issue by lolrepeatlol** [paulgazz/kmax#273]
# Description
- Depending on the commits provided, `klocalizer` can attempt to look for a non-existent file path, which causes an AssertionError in Python.
- It is likely that this AssertionError is due to a path resolution error.

# Steps to reproduce
## Steps followed
To get a repaired configuration file for a commit range, I followed the steps [here](https://github.com/paulgazz/kmax/blob/master/docs/advanced.md#getting-configuration-files-to-build-commit-ranges-and-using-exclude):

1. Clone the Linux kernel with `git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git` and enter the directory.
2. Create a diff from a range of patches using `git diff {commit1}..{commit2} > patchset.diff`. I initially encountered this issue with the range `541b80216cd1d511841c3c8d9559a7b13f4f79f2` to `0df2ac59bebfac221463ef57ed3554899b41d75f`.
3. Check out the source code at the latest of the two commits and create a kernel configuration file with a command like `make allnoconfig`. 
4. Run `klocalizer` with `klocalizer --repair .config -a x86_64 --include-mutex patchset.diff`.
## What I expected to happen
1. I expected `klocalizer` to repair the kernel configuration file.
## What actually happened
1. klocalizer runs into an AssertionError:
```
WARNING: No cached formulas for e98bee58dd93 available for download :(
Traceback (most recent call last):
  File "/home/alexei/.local/bin/klocalizer", line 1726, in <module>
    klocalizerCLI()
  File "/home/alexei/.local/bin/klocalizer", line 810, in klocalizerCLI
    assert os.path.isfile(srcfile_fullpath)
AssertionError
alexei@turing:~/LinuxKernels/hybridtest/linuxhybrid$
```

# Additional details
* I applied the following debug code to the `klocalizerCLI` file around line 810:
```
 global_scope_lines = {} # { unit : set(int) }, lines outside any ifdefs
  for target_list in [include_list, include_mutex_list, exclude_list]:
    for i, (unit, line_list) in enumerate(target_list):
      if line_list:
        srcfile = unit2srcfile(unit)
        srcfile_fullpath = os.path.join(linux_ksrc, srcfile)
        print(f"DEBUG: srcfile: {srcfile}, srcfile_fullpath: {srcfile_fullpath}. About to assert os.path.isfile...")  # debugging line
        assert os.path.isfile(srcfile_fullpath)  # affected line
```
which produced this debugging output:
```
DEBUG: srcfile: net/mptcp/pm_netlink.c, srofile_fullpath: ./net/mptcp/pm_netlink.c. About to assert os.path.isfile...
DEBUG: srcfile: net/sctp/input.c, srcfile_fullpath: ./net/sctp/input.c. About to assert os.path.isfile...
DEBUG: srcfile: sound/core/seq/seq_ump_convert.c, srcfile_fullpath: ./sound/core/seq/seq_ump_convert.c. About to assert os.path.isfile...
DEBUG: srcfile: sound/core/ump_convert.c, srofile_fullpath: ./sound/core/ump_convert.c. About to assert os.path.isfile...
DEBUG: srcfile: sound/firewire/amdtp-stream.c, srofile_fullpath: ./sound/firewire/amdtp-stream.c. About to assert os.path.isfile...
DEBUG: srcfile: sound/pci/hda/hda_generic.c, srcfile_fullpath: ./sound/pci/hda/hda_generic.c. About to assert os.path.isfile...
DEBUG: srcfile: sound/pci/hda/hda_intel.c, srcfile_fullpath: ./sound/pci/hda/hda_intel.c. About to assert os.path.isfile...
DEBUG: srcfile: sound/pci/hda/patch_conexant.c, srcfile_fullpath: ./sound/pci/hda/patch_conexant.c. About to assert os.path.isfile...
DEBUG: srcfile: sound/pci/hda/patch_realtek.c, srofile_fullpath: ./sound/pci/hda/patch_realtek.c. About to assert os.path.isfile...
DEBUG: srcfile: sound/usb/stream.c, srcfile_fullpath: ./sound/usb/stream.c. About to assert os path.isfile...
DEBUG: srcfile: arch/x86/kvm/../../../virt/kvmguest_memfd.c, srcfile_fullpath: ./arch/x86/kvm/../../../virt/kvmguest_memfd.c. About to assert os.path.isfile...
Traceback (most recent call last):
File "/home/alexei/.local/bin/klocalizer", line 1728, in <module>
klocalizerCLI()
File "/home/alexei/.local/bin/klocalizer", line 811, in klocalizerCLI
assert os.path.isfile(srcfile_fullpath) # affected line
AssertionError
alexei@turing:~/LinuxKernels/hybridtest/linuxhybrid$
```

* I noticed that `/arch/x86/kvm/../../../virt/kvmguest_memfd.c` does not exist and this file can't be found either as a compiled unit file, or a C file, in the Linux kernel, even when many KVM and virtualization options are turned on in the kernel build.
* The closest file in the provided diff was `/virt/kvm/guest_memfd.c`.

**Comment by lolrepeatlol** [comment]
Addressed by the professor in #279.

**Comment by TOBESTONG** [comment]
I'm not sure why I still encounter such assertion errors so frequently:
My final_patch.diff file is a merge of 10,000 individual patches. Referred to the krepair paper and used --no-merges to filter out non-empty patches containing .c and .h.
My final_patch.diff file is a merge of 10,000 individual patches. Referred to the krepair paper and used --no-merges to filter out non-empty patches containing .c and .h.
After I removed the problematic part of the patch, klocalizer continued. I'm curious to know what the tool now requires for patches.

```
wbz@shy-Super-Server:~/source/kernel/linux$ klocalizer --repair .config -a x86_64 --compile-jobs 128 --include-mutex /home/wbz/source/paper/patch/asset/patches/final_patch.diff -o /home/wbz/source/kernel/linux/repaired_configs/6.9-6.10 -v
klocalizer, kmax 4.8
INFO: Diff file was given as input ("/home/wbz/source/paper/patch/asset/patches/final_patch.diff"): assuming it was applied to the Linux source.
DEBUG: Computing the target lines from the patch file "/home/wbz/source/paper/patch/asset/patches/final_patch.diff"
DEBUG: Writing the patch target c lines to "/home/wbz/source/paper/patch/asset/patches/final_patch.diff.kloc_targets"
DEBUG: Computing the build system id for the Linux source..
DEBUG: Build system id: 80a76f39465e
DEBUG: Looking up cache index: https://configtools.org/klocalizer/cache/80a76f39465e
WARNING: No cached formulas for 80a76f39465e available for download :(
DEBUG: Approximate configs: {'default': '.config'}
DEBUG: No prebuilt kmax formulas.  Running kmax on demand with kmax cache file: ./.kmax/80a76f39465e/kmax_cache
DEBUG: Doing syntax analysis on "arch/alpha/kernel/asm-offsets.c" to get constrained line ranges.
DEBUG: Syntax analysis for "arch/alpha/kernel/asm-offsets.c" found 6 unconstrained lines, 0 lines are remaining for presence condition analysis.
DEBUG: Doing syntax analysis on "arch/alpha/kernel/bugs.c" to get constrained line ranges.
DEBUG: Syntax analysis for "arch/alpha/kernel/bugs.c" found 1 unconstrained lines, 0 lines are remaining for presence condition analysis.
DEBUG: Doing syntax analysis on "arch/alpha/kernel/console.c" to get constrained line ranges.
DEBUG: Syntax analysis for "arch/alpha/kernel/console.c" found 1 unconstrained lines, 0 lines are remaining for presence condition analysis.
DEBUG: Doing syntax analysis on "arch/alpha/kernel/core_cia.c" to get constrained line ranges.
DEBUG: Syntax analysis for "arch/alpha/kernel/core_cia.c" found 2 unconstrained lines, 4 lines are remaining for presence condition analysis.
DEBUG: Doing syntax analysis on "arch/alpha/kernel/core_irongate.c" to get constrained line ranges.
DEBUG: Syntax analysis for "arch/alpha/kernel/core_irongate.c" found 0 unconstrained lines, 1 lines are remaining for presence condition analysis.
Traceback (most recent call last):
  File "/home/wbz/.local/bin/klocalizer", line 1726, in <module>
    klocalizerCLI()
  File "/home/wbz/.local/bin/klocalizer", line 810, in klocalizerCLI
    assert os.path.isfile(srcfile_fullpath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

```
